### ISSUE TITLE
Getting error while deploying the global script.

### ISSUE THREAD

**Issue by Mgupta1003** [odoodo/Mirth-MetaAppender#3]
Hello 

Whenever we are trying to capture the channel Level Mirth logs using the step we are getting below error 

ERROR 2023-03-14 21:05:23,313 [Main Server Thread] com.mirth.connect.server.util.javascript.JavaScriptUtil: Error executing Deploy script from channel: Global
java.lang.NoClassDefFoundError: com/mirth/connect/plugins/serverlog/ServerLogItem
    at lu.hrs.mirth.MetaAppender.<init>(MetaAppender.java:290)
    at lu.hrs.mirth.MetaAppender.getInstance(MetaAppender.java:263)
    at lu.hrs.mirth.MetaAppender.setFocus(MetaAppender.java:77)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
    at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
    at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1479)
    at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815)
    at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
    at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:393)
    at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3280)
    at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:120)
    at com.mirth.connect.server.util.javascript.JavaScriptTask.executeScript(JavaScriptTask.java:150)
    at com.mirth.connect.server.util.javascript.JavaScriptUtil.executeScript(JavaScriptUtil.java:542)
    at com.mirth.connect.server.util.javascript.JavaScriptUtil$4.doCall(JavaScriptUtil.java:437)
    at com.mirth.connect.server.util.javascript.JavaScriptTask.call(JavaScriptTask.java:113)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.mirth.connect.plugins.serverlog.ServerLogItem
    at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 23 more

Can you Please help how we can overcome this .

**Comment by odoodo** [comment]
You're most probably using an older version of the MetaAppender on Mirth version 4.1 or higher. These versions are using log4j2. Please replace your MetaAppender by the latest version which supports both log4j versions.
